function handleError(name) {
    return function decorator(t, n, descriptor) {
        const original = descriptor.value;
        if (typeof original === 'function') {
            descriptor.value = function (...args) {
                try {
                    const result = original.apply(this, args);
                    return result.catch(function (response) {
                        console.log(response);
                    });
                } catch (e) {
                    console.log(`Error from ${name}: ${e}`);                    
                    throw e;
                }
            }
        }
        return descriptor;
    };
}

export default handleError;